// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TeaDriven.Avalonia.LocalizationProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("TeaDriven.Avalonia.LocalizationProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing TeaDriven.Avalonia.LocalizationProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TeaDriven.Avalonia.LocalizationProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "TeaDriven.Avalonia.LocalizationProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing TeaDriven.Avalonia.LocalizationProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
