// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TeaDriven.AvaloniaLocalization.FSharp.Runtime")>]
[<assembly: AssemblyProductAttribute("TeaDriven.AvaloniaLocalization.FSharp")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing TeaDriven.AvaloniaLocalization.FSharp.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TeaDriven.AvaloniaLocalization.FSharp.Runtime"
    let [<Literal>] AssemblyProduct = "TeaDriven.AvaloniaLocalization.FSharp"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing TeaDriven.AvaloniaLocalization.FSharp."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
